### ISSUE TITLE
nameError does not display correctly

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#14]
```python
x = 1
y = 2
z
```

> console.ts:123 [Extension Host] WOOF: [{"source": "z", "lineno": 3, "error": true, "value": "NameError: name 'z' is not defined\n"}]

> WOOF: [{"source": "z", "lineno": 3, "error": true, "value": "NameError: name 'z' is not defined\n"}, {"source": "z", "lineno": 3, "value": "None"}, {"source": "z", "lineno": 3, "value": "None"}, {"source": "", "lineno": 112, "error": true, "value": "TimeoutError: 'Wolf timed out after [10 seconds] exceeded!'\n"}]
 (at PythonTracer.tryParsePythonData (C:\Users\almenon\.vscode\extensions\traBpUkciP.wolf-0.2.5\out\src\tracer.js:46:25))
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:394
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104

> console.ts:123 [Extension Host] SyntaxError: Unexpected token W in JSON at position 97
	at JSON.parse (<anonymous>)
	at PythonTracer.tryParsePythonData (C:\Users\almenon\.vscode\extensions\traBpUkciP.wolf-0.2.5\out\src\tracer.js:42:29)
	at Socket.__dirname.tracePythonScript.python.stdout.on (C:\Users\almenon\.vscode\extensions\traBpUkciP.wolf-0.2.5\out\src\tracer.js:30:38)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20) (at PythonTracer.tryParsePythonData (C:\Users\almenon\.vscode\extensions\traBpUkciP.wolf-0.2.5\out\src\tracer.js:47:25))

The following also fails:
```python
x
```

**Comment by Almenon** [comment]
Almost forgot to mention - win 10, python 3.5

**Comment by Almenon** [comment]
the two issues I raised today were on the latest version of the 0.3.0 branch

**Comment by Almenon** [comment]
but maybe you get the same issue with released, let me check

**Comment by Duroktar** [comment]
Are you sure? The error code you pasted shows this..
> SNIP...
> ...at Pipe.onread (net.js:560:20) (at PythonTracer.tryParsePythonData >
> (C:\Users\almenon.vscode\extensions\traBpUkciP.wolf-0.2.5\out\src\tracer.js:47:25))

**Comment by Almenon** [comment]
errrr..... not sure what happened there lol.  I ran it again and looks like I'm using the right version this time:



> console.ts:123 [Extension Host] WOOF: [{"lineno": 1, "value": "None", "source": "x"}, {"lineno": 1, "error": true, "value": "NameError: name 'x' is not defined\n", "source": "x"}]

> WOOF: [{"lineno": 1, "value": "None", "source": "x"}, {"lineno": 1, "error": true, "value": "NameError: name 'x' is not defined\n", "source": "x"}, {"lineno": 1, "value": "None", "source": "x"}, {"lineno": 1, "value": "None", "source": "x"}, {"lineno": 112, "error": true, "value": "TimeoutError: 'Wolf timed out after [10 seconds] exceeded!'\n", "source": ""}]
 (at PythonTracer.tryParsePythonData (C:\dev\Wolf\out\src\tracer.js:54:25))
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:394
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104

> console.ts:123 [Extension Host] SyntaxError: Unexpected token W in JSON at position 144
	at JSON.parse (<anonymous>)
	at PythonTracer.tryParsePythonData (C:\dev\Wolf\out\src\tracer.js:50:29)
	at Socket.__dirname.tracePythonScriptForDocument.python.stdout.on (C:\dev\Wolf\out\src\tracer.js:38:38)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20) (at PythonTracer.tryParsePythonData (C:\dev\Wolf\out\src\tracer.js:55:25))

I also made sure I'm on the v0.3.0 branch

**Comment by Duroktar** [comment]
Fixed in 0.3.0 upcoming release.

**Comment by Almenon** [comment]
? I'm still getting the same error.  Which commit fixed it?

**Comment by Duroktar** [comment]
I'm not sure which one exactly, I made about 14 commits today. But the most recent master branch (it's not on the extension store yet, just here) will be the latest version.

**Comment by Duroktar** [comment]
<img width="449" alt="almenonerror1" src="https://user-images.githubusercontent.com/19689932/37248546-6d41c8ec-24ab-11e8-9b42-8ea6d09595e7.png">

----

<img width="447" alt="almenonerror2" src="https://user-images.githubusercontent.com/19689932/37248547-6ef0a898-24ab-11e8-8bd6-f08683bc2f4a.png">

**Comment by Almenon** [comment]
I switched to master and It is still not working - same error.

**Comment by Duroktar** [comment]
Oh I forgot I have a windows laptop now lol I got one for work, so I can try it out myself on windows 10 (I think that it may be an OS thing). Thanks for checking on it, I'll post back with an update soon..

**Comment by Duroktar** [comment]
I was able to replicate that exact error and traced it back to the timeout function in our `wolf.py` file. So I moved the timeout to the extension and that seems to have fixed it for good.

**Comment by Duroktar** [comment]
Closing. Feel free to re-open should the issue persist.
